Simplified adding the github token permision

diff --git a/.github/workflows/token-permission-new.yml b/.github/workflows/token-permission-new.yml
--- a/.github/workflows/token-permission-new.yml
+++ b/.github/workflows/token-permission-new.yml
@@ -15,21 +15,21 @@ jobs:
     - name: Find YML Files
       id: find-yml
       run: |
-        file_list=$(find .github/workflows -type f -name "*.yml" -not -name 'token-permission.yml' -printf '%p,' | sed 's/,$//')
-        file_list="[\"$(echo "$file_list" | sed 's/,/\",\"/g')\"]"
+        file_list=$(find .github/workflows -type f -name "*.yml" -not -name 'token-permission.yml')
+        IFS=',' read -r -a files <<< "$file_list"
         echo "File List: $file_list"
-        echo "::set-output name=file-list::$file_list"
+        echo "::set-output name=file-list::${files[@]}"
 
     - name: Check and Add Permissions Block
       run: |
-        file_list="${{ steps.find-yml.outputs.file-list }}"
-        for file_path in $file_list; do
-        if ! grep -q "permissions:" "$file_path"; then
-            echo "Permissions block not found in $file_path. Adding..."
-            sed -i -e '/^jobs:/i \permissions: write-all\n' "$file_path"
-        else
-            echo "Permissions block found in $file_path. Skipping..."
-        fi
+        file_list=("${{ steps.find-yml.outputs.file-list }}")
+        for file_path in "${file_list[@]}"; do
+            if ! grep -q "permissions:" "$file_path"; then
+                echo "Permissions block not found in $file_path. Adding..."
+                sed -i -e '/^jobs:/i \permissions: write-all\n' "$file_path"
+            else
+                echo "Permissions block found in $file_path. Skipping..."
+            fi
         done
 
     - name: Check for Changes
