Changing the approach

diff --git a/.github/workflows/token-permission.yml b/.github/workflows/token-permission.yml
--- a/.github/workflows/token-permission.yml
+++ b/.github/workflows/token-permission.yml
@@ -25,17 +25,16 @@ jobs:
     - name: Add Permissions Block
       run: |
         for file in $(find .github/workflows -name '*.yml' -not \( -name 'token-permission.yml' -o -name 'add-license-file.yml' \)); do
-            python script/check_permission_block.py "$file"
-            status=$?
-            if [ $status -eq 0 ]; then
-              echo "Permissions block found. Continuing..."
-            elif [ $status -eq 1 ]; then
-              echo "Permissions block not found. Adding permissions block..."
-              sed -i '/^jobs:/i \npermissions : write-all' "$file"
-            else
-              echo "Error in checking permissions block."
-              exit 1
-            fi
+        permissions_found=$(python script/check_permission_block.py "$file")
+          if [ "$permissions_found" == "true" ]; then
+            echo "Permissions block found. Continuing..."
+          elif [ "$permissions_found" == "false" ]; then
+            echo "Permissions block not found. Adding permissions block..."
+            sed -i '/^jobs:/i \npermissions : write-all' "$file" || true
+          else
+            echo "Error in checking permissions block."
+            exit 1
+          fi
         done
 
     - name: Check for Changes
