Back to matrix approach

diff --git a/.github/workflows/token-permission.yml b/.github/workflows/token-permission.yml
--- a/.github/workflows/token-permission.yml
+++ b/.github/workflows/token-permission.yml
@@ -4,108 +4,108 @@ on:
   workflow_dispatch:
 
 jobs:
-  # generate-file-list:
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     file-list: ${{ steps.list-files.outputs.file-list }}
-  #   # outputs:
-  #   #   artifacts: ${{ steps.set-output.outputs.file-list }}
-
-  #   steps:
-  #     - name: Checkout Repository
-  #       uses: actions/checkout@v4
-  #       with:
-  #         token: ${{ secrets.GK_PAT }}
-
-  #     - name: Set Output
-  #       id: list-files
-  #       run: |
-  #         file-list=$(find .github/workflows -type f -name "*.yml" -print | tr '\n' ',' | sed 's/,$$//')
-  #         echo ${{ matrix.file }}-list
-
-  #     - name: Set output
-  #       run: echo "::set-output name=file-list::${{ steps.list-files.outputs.file-list }}"
-  #         # file-list=$(ls $GITHUB_WORKSPACE/.github/workflows/*.yml | grep -v 'token-permission.yml' || true)
-  #         # echo "File list: ${{ matrix.file }}-list"
-  #         # echo "::set-output name=file-list::${{ matrix.file }}-list"
-       
-  add-permissions-block:
+  generate-file-list:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        files: ${{fromJson(needs.set_files.outputs.files)}}
-        #file: [".github/workflows/github-rest-api1.yml",".github/workflows/github-rest-api2.yml"]
-        #paths-ignore: ["**/token-permission.yml"]
-      max-parallel: 1
+    outputs:
+      file-list: ${{ steps.set-output.outputs.file-list }}
+    # outputs:
+    #   artifacts: ${{ steps.set-output.outputs.file-list }}
+
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v4
-      with:
-        token: ${{ secrets.GK_PAT }}
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GK_PAT }}
 
-    - name: Install Python
-      uses: actions/setup-python@v3
-      with:
-        python-version: 3.x
+      - name: Set Output
+        id: set-output
+        run: |
+          file-list=$(find .github/workflows -type f -name "*.yml" -not -name 'token-permission.yml' -print | tr '\n' ',' | sed 's/,$$//')
+          echo "::set-output name=file-list::$file-list"
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install ruamel.yaml
+      # - name: Set output
+      #   run: echo "::set-output name=file-list::${{ steps.list-files.outputs.file-list }}"
+          # file-list=$(ls $GITHUB_WORKSPACE/.github/workflows/*.yml | grep -v 'token-permission.yml' || true)
+          # echo "File list: ${{ matrix.file }}-list"
+          # echo "::set-output name=file-list::${{ matrix.file }}-list"
+       
+  # add-permissions-block:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       #files: ${{ needs.set_files.outputs.files }}
+  #       file: [".github/workflows/github-rest-api1.yml",".github/workflows/github-rest-api2.yml"]
+  #       #paths-ignore: ["**/token-permission.yml"]
+  #     max-parallel: 1
+  #   steps:
+  #   - name: Checkout Repository
+  #     uses: actions/checkout@v4
+  #     with:
+  #       token: ${{ secrets.GK_PAT }}
 
-    - name: Set files
-      id: set_files
-      run: |
-        mapfile -t files < <(find .github/workflows -type f -name "*.yml" -not -name 'token-permission.yml')
-        echo "::set-output name=files::${files[*]}"
+  #   - name: Install Python
+  #     uses: actions/setup-python@v3
+  #     with:
+  #       python-version: 3.x
 
-    - name: Set matrix variables
-      run: |
-        echo "file=${{ steps.set_files.outputs.files }}" >> $GITHUB_ENV
-      shell: bash
+  #   - name: Install dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       pip install ruamel.yaml
 
-    - name: Add Permissions Block
-      id: add_permissions
-      run: |
-        python script/check_permissions.py "${{ matrix.file }}"
+  #   - name: Set files
+  #     id: set_files
+  #     run: |
+  #       mapfile -t files < <(find .github/workflows -type f -name "*.yml" -not -name 'token-permission.yml')
+  #       echo "::set-output name=files::${files[*]}"
 
-    - name: Check for Permissions
-      id: check_permissions
-      run: |
-          echo "Permissions found: ${{ steps.add_permissions.outputs.permissions_found }}"
+  #   - name: Set matrix variables
+  #     run: |
+  #       echo "file=${{ steps.set_files.outputs.files }}" >> $GITHUB_ENV
+  #     shell: bash
 
-    - name: Take Action based on Permissions
-      run: |
-          if [ "${{ steps.add_permissions.outputs.permissions_found }}" == "false" ]; then
-            echo "Permissions block not found. Adding permissions block..."
-            echo "File path: ${{ matrix.file }}"
-            sed -i -e '/^jobs:/i \permissions: write-all\n' ${{ matrix.file }}
-          else
-            echo "Permissions block found. Continuing..."
-          fi
-      shell: bash
+  #   - name: Add Permissions Block
+  #     id: add_permissions
+  #     run: |
+  #       python script/check_permissions.py "${{ matrix.files }}"
 
-    - name: Check for Changes
-      id: check_changes
-      run: |
-        if git diff --quiet; then
-        echo "No changes to commit. Skipping commit step."
-        echo "::set-output name=changes::false"
-        else
-        echo "::set-output name=changes::true"
-        fi
-      shell: bash
+  #   - name: Check for Permissions
+  #     id: check_permissions
+  #     run: |
+  #         echo "Permissions found: ${{ steps.add_permissions.outputs.permissions_found }}"
 
-    - name: Commit Changes
-      if: steps.check_changes.outputs.changes == 'true'
-      run: |
-        git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
-        git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
-        git add .
-        git commit -m "Added Permission Block- $(date +"%Y-%m-%d %H:%M:%S")"
-        git push # Replace 'branch-name' with the branch name
-      env:
-        GITHUB_WORKSPACE: ${{ github.workspace }}
-        GITHUB_TOKEN: ${{ secrets.GK_PAT }}
+  #   - name: Take Action based on Permissions
+  #     run: |
+  #         if [ "${{ steps.add_permissions.outputs.permissions_found }}" == "false" ]; then
+  #           echo "Permissions block not found. Adding permissions block..."
+  #           echo "File path: ${{ matrix.files }}"
+  #           sed -i -e '/^jobs:/i \permissions: write-all\n' ${{ matrix.files }}
+  #         else
+  #           echo "Permissions block found. Continuing..."
+  #         fi
+  #     shell: bash
+
+  #   - name: Check for Changes
+  #     id: check_changes
+  #     run: |
+  #       if git diff --quiet; then
+  #       echo "No changes to commit. Skipping commit step."
+  #       echo "::set-output name=changes::false"
+  #       else
+  #       echo "::set-output name=changes::true"
+  #       fi
+  #     shell: bash
+
+  #   - name: Commit Changes
+  #     if: steps.check_changes.outputs.changes == 'true'
+  #     run: |
+  #       git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
+  #       git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
+  #       git add .
+  #       git commit -m "Added Permission Block- $(date +"%Y-%m-%d %H:%M:%S")"
+  #       git push # Replace 'branch-name' with the branch name
+  #     env:
+  #       GITHUB_WORKSPACE: ${{ github.workspace }}
+  #       GITHUB_TOKEN: ${{ secrets.GK_PAT }}
 
 
