Lets make this simple approach work

diff --git a/.github/workflows/token-permission.yml b/.github/workflows/token-permission.yml
--- a/.github/workflows/token-permission.yml
+++ b/.github/workflows/token-permission.yml
@@ -35,17 +35,17 @@ jobs:
     #         echo "Checking permissions in: $file_path"
     #         grep "permissions:" "$file_path" || true
     #     done
-    # - name: Check and Add Permissions Block
-    #   run: |
-    #     file_list="${{ steps.find-yml.outputs.file-list }}"
-    #     for file_path in $file_list; do
-    #         if ! grep -q "permissions:" "$file_path"; then
-    #             echo "Permissions block not found in $file_path. Adding..."
-    #             sed -i -e '/^jobs:/i \permissions: write-all\n' "$file_path"
-    #         else
-    #             echo "Permissions block found in $file_path. Skipping..."
-    #         fi
-    #     done
+    - name: Check and Add Permissions Block
+      run: |
+        file_list="${{ steps.find-yml.outputs.file-list }}"
+        for file_path in $file_list; do
+            if ! grep -q "permissions:" "$file_path"; then
+                echo "Permissions block not found in $file_path. Adding..."
+                sed -i -e '/^jobs:/i \permissions: write-all\n' "$file_path"
+            else
+                echo "Permissions block found in $file_path. Skipping..."
+            fi
+        done
 
     # - name: Check for Changes
     #   id: check_changes
